Python activities issues 34, 35 and 36
UiPath/Community.Activities pull request #71
Opened 2020-11-09 12:47 UTC by petcua1

The following issues have been resolved:
https://github.com/UiPath/Community.Activities/issues/34
https://github.com/UiPath/Community.Activities/issues/35
https://github.com/UiPath/Community.Activities/issues/36(Which is related to #35)
Now the version is inferred from running python --version in the folder where Python is installed and Version field in the activity is now hidden.

2020-11-10 09:10 UTC, adrian-zanescu requested changes

2020-11-10 09:10 UTC, adrian-zanescu commented on Activities/Database/UiPath.Database/DatabaseConnection.cs
> +            if (_connection.GetType() == typeof(OdbcConnection)
this is not a python fix. split these in 2 different prs

2020-11-10 09:10 UTC, adrian-zanescu commented on Activities/Python/UiPath.Python/Properties/UiPath.Python.fr.resx
> +  <data name="UnsupportedVersionException" xml:space="preserve">
remove this from the commit

2020-11-10 09:10 UTC, adrian-zanescu commented on Activities/Python/UiPath.Python/Version.cs
> +        internal static Version GetVersionFromStr(this string fileVersion)
a unit test would be nice

2020-11-10 18:57 UTC, petcua1 reviewed
All the changes have been resolved

2020-11-10 18:57 UTC, petcua1 commented on Activities/Python/UiPath.Python/Properties/UiPath.Python.fr.resx
> +  <data name="UnsupportedVersionException" xml:space="preserve">
Was there by mistake. I have removed

2020-11-11 07:00 UTC, adrian-zanescu requested changes

2020-11-11 07:01 UTC, adrian-zanescu commented on Activities/Python/UiPath.Python/Version.cs
> +        internal static Version GetVersionFromStr(this string fileVersion)
still no tests

2020-11-12 13:29 UTC, adrian-zanescu approved these changes

2020-11-12 13:30 UTC, merged